FROM golang:1.20-alpine3.16 as build

ENV CGO_ENABLED 0
ARG BUILD_REF

# Copy the source code into the container.
COPY . /balancer

# Build the admin binary.
WORKDIR /balancer
RUN go build cmd/main.go


# Run the Go Binary in Alpine.
FROM alpine:3.17
COPY --from=build /balancer /balancer
WORKDIR /balancer
CMD ["./main"]
